@startuml
'https://plantuml.com/class-diagram
MonsterType <|.. Card: uses
ElementType <|.. Card: uses
Deck <-- User: has
Card <-- User: needs
Stack <-- User: has
CardType <|.. Card: uses
MonsterCard -- Card: inherits (child class)
SpellCard -- Card: inherits (child class)

class User {

    -username: String
    -password: String
    -coins: int
    -Deck: Deck
    -Stack: Stack
    -elo: int
    -wins: int
    -losses: int
    -games: int
    +win(): void
    +lose(): void
    +draw(): void
    +buyPackage(): void
    +eloCalculator(): void

}

class Deck {

    -Deck: LinkedList<Card>
    -Cards: int
    +randomCard(): Card


}
class Card {

    #name: String
    #damage: int
    #type: ElementType
    #monsterType: MonsterType

}
class MonsterCard {
    -cardType: CardType
}

class SpellCard {
    -cardType: CardType
}
enum CardType {

    Monster, Spell

}
 class Stack {

    -Stack: LinkedList<Card>
    +addCard(Card): void
    +removeCard(): void


}

enum ElementType {

    FIRE, WATER, NORMAL
    +generateElement(): ElementType
    +generateDamage(): int

}

enum MonsterType {

    GOBLIN, DRAGON, WIZARD,
    ORK, KNIGHT, KRAKEN,
    ELVE, TROLL, NORMAL

    +generateMonster(): MonsterType


}

class Battle(){


}

@enduml